In [7]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, precision_score, recall_score
from sklearn.neighbors import KNeighborsClassifier
import joblib

In [13]:
features_to_use = ['lbp', 'hog', 'color', 'gabor'] #Added all features for baseline


models = {
    'Random Forest': RandomForestClassifier(random_state=1),
    'Gradient Boosting': GradientBoostingClassifier(random_state=1),
    'SVM': SVC(random_state=1),
    'KNN': KNeighborsClassifier(n_neighbors=10)
}

In [14]:
#These functions help set a loop/pipeline for experimenting with different features/models.
def load_and_combine_features(real_path, fake_path, features_to_use):
    #We load real and fake features, combine them with labels.
    real_data = np.load(real_path)
    fake_data = np.load(fake_path)

    #Print individual feature dimensions.
    print(f"  Feature dimensions in {real_path}:")
    for feature in features_to_use:
        print(f"    {feature}: {real_data[feature].shape[1]} features")
    
    #We extract and concatenate selected features.
    real_features = np.concatenate([real_data[feature] for feature in features_to_use], axis=1)
    fake_features = np.concatenate([fake_data[feature] for feature in features_to_use], axis=1)

    #We combine real and fake images.
    X = np.vstack([real_features, fake_features])
    y = np.hstack([np.zeros(len(real_features)), np.ones(len(fake_features))])
    return X, y

def print_metrics(y_true, y_pred, dataset_name, model_name):
    #We choose the following evaluation metrics.
    Acc = accuracy_score(y_true, y_pred)
    F1 = f1_score(y_true, y_pred)
    Precision = precision_score(y_true, y_pred)
    Recall = recall_score(y_true, y_pred)
    cm = confusion_matrix(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    
    # Extract confusion matrix values
    tn, fp, fn, tp = cm.ravel()

    print(f"\n{model_name} - {dataset_name} Results:")
    print(f" Accuracy: {Acc:.4f}")
    print(f" Precision: {Precision:.4f}")
    print(f" Recall: {Recall:.4f}")
    print(f" F1 Score: {F1:.4f}")
    print(f" Confusion Matrix:")
    print(f"   {cm}")

    print(f"\n CONFUSION MATRIX BREAKDOWN:")
    print(f"  True Negatives  (TN): {tn:4d} - Correctly identified as Fake")
    print(f"  False Positives (FP): {fp:4d} - Fake wrongly identified as Real")
    print(f"  False Negatives (FN): {fn:4d} - Real wrongly identified as Fake")
    print(f"  True Positives  (TP): {tp:4d} - Correctly identified as Real")
    
    # Error analysis
    total_errors = fp + fn
    total_samples = len(y_true)
    print(f"\n ERROR ANALYSIS:")
    print(f"  Total Errors: {total_errors}/{total_samples} ({total_errors/total_samples*100:.2f}%)")
    print(f"  False Positives: {fp} ({fp/total_samples*100:.2f}%) - Fake images classified as Real")
    print(f"  False Negatives: {fn} ({fn/total_samples*100:.2f}%) - Real images classified as Fake")
    

In [20]:
#Time to load the data.
print("\n--- Train ---")
X_train, y_train = load_and_combine_features(
    'train_real_all_features.npz',
    'train_fake_all_features.npz',
    features_to_use
)
print("\n--- Validation ---")
X_valid, y_valid = load_and_combine_features(
    'valid_real_all_features.npz',
    'valid_fake_all_features.npz',
    features_to_use
)
print("\n--- Test ---")
X_test, y_test = load_and_combine_features(
    'test_real_all_features.npz',
    'test_fake_all_features.npz',
    features_to_use
)

print(f"\nTrain set: {X_train.shape}, Valid set: {X_valid.shape}, Test set: {X_test.shape}")
print(f"Total features used: {X_train.shape[1]}")

print("\n--- Class Balance ---")
print(f"Train - Real: {np.sum(y_train == 0)}, Fake: {np.sum(y_train == 1)}")
print(f"Valid - Real: {np.sum(y_valid == 0)}, Fake: {np.sum(y_valid == 1)}")
print(f"Test  - Real: {np.sum(y_test == 0)}, Fake: {np.sum(y_test == 1)}")


--- Train ---
  Feature dimensions in train_real_all_features.npz:
    lbp: 59 features
    hog: 1764 features
    color: 6 features
    gabor: 8 features

--- Validation ---
  Feature dimensions in valid_real_all_features.npz:
    lbp: 59 features
    hog: 1764 features
    color: 6 features
    gabor: 8 features

--- Test ---
  Feature dimensions in test_real_all_features.npz:
    lbp: 59 features
    hog: 1764 features
    color: 6 features
    gabor: 8 features

Train set: (10000, 1837), Valid set: (2000, 1837), Test set: (2000, 1837)
Total features used: 1837

--- Class Balance ---
Train - Real: 5000, Fake: 5000
Valid - Real: 1000, Fake: 1000
Test  - Real: 1000, Fake: 1000


In [21]:
#Scaling all features.
print("\nScaling features...")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

#Save scaler
joblib.dump(scaler, 'scaler.joblib')
print("Scaler saved to 'scaler.joblib'")


Scaling features...
Scaler saved to 'scaler.joblib'


In [22]:
#Time to train and evaluate all models.
trained_models = {}

for model_name, model in models.items():
    print(f"\n{'+'*50}")
    print(f"Training {model_name} ...")

    #Training.
    model.fit(X_train_scaled, y_train)

    #Predicting on all sets.
    y_train_pred = model.predict(X_train_scaled)
    y_valid_pred = model.predict(X_valid_scaled)
    y_test_pred = model.predict(X_test_scaled)

    #Printing metrics.
    print_metrics(y_train, y_train_pred, "Train", model_name)
    print_metrics(y_valid, y_valid_pred, "Valid", model_name)
    print_metrics(y_test, y_test_pred, "Test", model_name)

    #Saving models.
    model_filename = f"{model_name.lower().replace(' ', '_')}_model.joblib"
    joblib.dump(model, model_filename)
    print(f"\nModel saved to '{model_filename}'")

    #Storing in dictionary.
    trained_models[model_name] = model

print("\n" + "="*50)
print("Baseline: All models trained and saved with all features (lbp, hog, color, gabor)")


++++++++++++++++++++++++++++++++++++++++++++++++++
Training Random Forest ...

Random Forest - Train Results:
 Accuracy: 1.0000
 F1 Score: 1.0000
 Confusion Matrix:
   [[5000    0]
 [   0 5000]]

Random Forest - Valid Results:
 Accuracy: 0.7370
 F1 Score: 0.7300
 Confusion Matrix:
   [[763 237]
 [289 711]]

Random Forest - Test Results:
 Accuracy: 0.7535
 F1 Score: 0.7428
 Confusion Matrix:
   [[795 205]
 [288 712]]

Model saved to 'random_forest_model.joblib'

++++++++++++++++++++++++++++++++++++++++++++++++++
Training Gradient Boosting ...

Gradient Boosting - Train Results:
 Accuracy: 0.8497
 F1 Score: 0.8524
 Confusion Matrix:
   [[4158  842]
 [ 661 4339]]

Gradient Boosting - Valid Results:
 Accuracy: 0.7540
 F1 Score: 0.7625
 Confusion Matrix:
   [[718 282]
 [210 790]]

Gradient Boosting - Test Results:
 Accuracy: 0.7655
 F1 Score: 0.7704
 Confusion Matrix:
   [[744 256]
 [213 787]]

Model saved to 'gradient_boosting_model.joblib'

+++++++++++++++++++++++++++++++++++++++++++++++